### ISSUE TITLE
Build error on Fedora 36

### ISSUE THREAD

**Issue by devrimgunduz** [df7cb/pg_filedump#10]
Hi,

pg_filedump 14.1 fails to build on Fedora 36 (gcc 12). Can you please take a look? Thanks ! Devrim

> gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection pg_filedump.o decode.o stringinfo.o  -L/usr/pgsql-14/lib -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,--build-id=sha1 -Wl,-dT,/var/lib/pgsql/rpm14/BUILD/postgresql-14.2/.package_note-postgresql14-14.2-3PGDG.f36.x86_64.ld -L/usr/lib64  -L/usr/lib64 -Wl,--as-needed -Wl,-rpath,'/usr/pgsql-14/lib',--enable-new-dtags   -L/usr/pgsql-14/lib -lpgcommon -lpgport -L/usr/pgsql-14/lib -lpq -llz4 -o pg_filedump
> *** WARNING *** there are active plugins, do not report this as a bug unless you can reproduce it without enabling any plugins.
> Event                            | Plugins
> PLUGIN_FINISH_UNIT               | annobin: Generate final annotations
> PLUGIN_START_UNIT                | annobin: Generate global annotations
> PLUGIN_ALL_PASSES_START          | annobin: Generate per-function annotations
> PLUGIN_ALL_PASSES_END            | annobin: Register per-function end symbols
> lto1: internal compiler error: Segmentation fault
> Please submit a full bug report, with preprocessed source.
> See <http://bugzilla.redhat.com/bugzilla> for instructions.
> lto-wrapper: fatal error: /usr/bin/gcc returned 1 exit status
> compilation terminated.
> /usr/bin/ld: error: lto-wrapper failed
> collect2: error: ld returned 1 exit status
> make[1]: *** [/usr/pgsql-14/lib/pgxs/src/makefiles/pgxs.mk:475: pg_filedump] Error 1
> make[1]: Leaving directory '/var/lib/pgsql/rpm14/BUILD/pg_filedump-REL_14_1'
> error: Bad exit status from /var/tmp/rpm-tmp.SxlJIT (%build)
>

**Comment by df7cb** [comment]
Hi Devrim, sorry for ignoring this issue so far. That's an internal compiler error, I don't think I can fix that on the pg_filedump side.
