### ISSUE TITLE
decompress_tmp_buff

### ISSUE THREAD

**Issue by mrmgrpl** [df7cb/pg_filedump#11]
Hi,
I'm trying to compile pg_filedump from source. I made changes to that variable (double the size of that buffer).
But when I try to compile I get errors and I know why.

```
To compile pg_filedump, you will need to have a properly configured
PostgreSQL source tree or complete install tree (with include files)
of the appropriate PostgreSQL major version.

```

I don't understand what's the "a properly configured PostgreSQL source tree"

I have downloaded source for postgresql from git, but how to point complier where that source is? or were to put that folder?

Can you just add a parameter for that variable, not to hardcode it in?

**Comment by df7cb** [comment]
Hi,

you just need the PG header files along with pg_config installed. Normal PGXS build incantation is this:

`make PG_CONFIG=/path/to/postgresql/bin/pg_config`
