### ISSUE TITLE
Question: Bloat Detection?

### ISSUE THREAD

**Issue by MichaelDBA** [df7cb/pg_filedump#13]
Can pg_filedump be used in some way to detect bloat or empty rows on a page?

**Comment by MichaelDBA** [comment]
Please leave the issue open so I can respond?

**Comment by MichaelDBA** [comment]
dont wanna have to create another issue

**Comment by MichaelDBA** [comment]
I have some important follow-up questions...

**Comment by df7cb** [comment]
You can still respond.

**Comment by MichaelDBA** [comment]
Also, by leaving it open, folks can see that there is activity here...

**Comment by MichaelDBA** [comment]
one thing for sure, this is the fastest closing issues pg site i even have been to, hehehe

**Comment by MichaelDBA** [comment]
ur a reputable guy in the pg community, come on...

**Comment by df7cb** [comment]
The issue is also still visible. :)

The thing you are asking for is out of scope for pg_filedump, that's why I closed it. I might be convinced otherwise, then we can reopen, but for that, you should provide more input instead of nagging.

**Comment by df7cb** [comment]
There is bloat from unvacuumed tuples (with xmax set, but perhaps that xmax did not commit?), and bloat from free space that has already been vacuumed. You should really use the pgstattuple extension for this, it's much easier and built for this purpose.

**Comment by MichaelDBA** [comment]
yeah, but the pgstattuple extension is expensive in production so I wouldn't want to run it a lot

**Comment by df7cb** [comment]
pg_filedump is just as expensive - it reads files from disk.
