### ISSUE TITLE
vector data

### ISSUE THREAD

**Issue by FlynnHuang8** [df7cb/pg_filedump#17]
Can you support parsing of -D vector, i.e. vector data?

**Comment by df7cb** [comment]
Hi, I guess you mean https://github.com/pgvector/pgvector ?

What's the use case for pg_filedump here? Non-core datatypes would best be extracted by getting PostgreSQL to run on the data directory, and just SELECTing the data.

**Comment by hhf-java** [comment]
When I build a vector index using pgvector, I want to use pg_dump to export the data and see the index structure, but it doesn't parse the HNSW index correctly, it would be great if it could support exporting!

**Comment by df7cb** [comment]
pg_dump won't look inside indexes.

If you want to look into page structures, try the `pageinspect` extension.

**Comment by df7cb** [comment]
Fwiw if someone submits a PR for hnsw index support, I wouldn't be opposed to merging it, but that's probably better handled first with in-PostgreSQL extensions.
