### ISSUE TITLE
Decode numeric(19,4) type become value as C723  

### ISSUE THREAD

**Issue by jasonchenTJ** [df7cb/pg_filedump#26]
Hi Guys,

When I try to decode the table file (which have a numeric(19,4)) , become value as 8550.C723. 

![image](https://github.com/df7cb/pg_filedump/assets/133334015/deee248e-b048-4db4-b2f7-c749cf983443)

My command like: /opt/pgsql-15/bin/pg_filedump -D  numeric,timestamp,numeric.. 
My PG version is 15.3.

So how can I fix it ? 

Thanks
Jason

**Comment by GetsuDer** [comment]
Hello! Can you, please, provide a little more context, such as example table columns and content on which this bug manifests?

Best regards,
Svetlana
