### ISSUE TITLE
v13  support?

### ISSUE THREAD

**Issue by devrimgunduz** [df7cb/pg_filedump#4]
Hi,

Any plans for v13 support?

Regards, Devrim

**Comment by df7cb** [comment]
Ouch, I'm on the radar!

Yeah I will have a look now. Thanks!

**Comment by devrimgunduz** [comment]
Hi,

ping :)

**Comment by df7cb** [comment]
Hi Devrim,
I just tagged 13.0.

The reason I didn't get to this earlier is because it didn't pop up in the list of packages I had to re-upload to Debian as we don't compile pg_filedump per PG version, but ship just one binary for all.

**Comment by devrimgunduz** [comment]
Thanks a log @df7cb ! Pushed RPMs yesterday.

Cheers, Devrim
